Repository Celesca/hacka-backend-elysia, pull requests merged in 2024-11, with the labels that each got.

#2 Feature : Swipe Functions Implementation
  bun.lockb
  package.json
  prisma/migrations/20241105061804_init/migration.sql
  prisma/migrations/migration_lock.toml
  prometheus.yml
  sonar-project.properties
  src/controllers/swipeController.ts
  src/controllers/userController.ts
  src/index.ts
  src/prisma.ts
Labels: enhancement

#5 Fix Bugs: Swipe Functions
  prisma/migrations/20241107160208_change/migration.sql
  prisma/schema.prisma
  src/controllers/skillController.ts
  src/controllers/userController.ts
Labels: bug, enhancement

#7 Feature : SkillController
  package.json
  prisma/migrations/20241107172051_cascade/migration.sql
  prisma/schema.prisma
  src/controllers/skillController.ts
  src/controllers/userController.ts
  src/index.ts
Labels: enhancement

#10 Feature : Messaging Controller
  src/controllers/messageController.ts
  src/controllers/userController.ts
  src/index.ts
Labels: enhancement, Not-ready

#16 Feature : Hackathon Lists
  prisma/migrations/20241117185133_hackathons/migration.sql
  prisma/schema.prisma
  src/controllers/hackathonController.ts
  src/index.ts
Labels: enhancement, Ready to merge

#18 Feature : Team Lists
  bun.lockb
  prisma/migrations/20241118165010_userteam/migration.sql
  prisma/schema.prisma
  src/controllers/messageController.ts
  src/controllers/notificationController.ts
  src/controllers/swipeController.ts
  src/controllers/teamController.ts
Labels: enhancement, Not-ready

#20 pull register from latest was Hongyok
  .env
  .gitignore
  bun.lockb
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/LoginForm.jsx
  frontend/src/Register.css
  frontend/src/Register.jsx
  frontend/src/Swipe.css
  frontend/src/Swipe.jsx
  frontend/src/assets/HY.png
  frontend/src/assets/bear.png
  frontend/src/assets/homebg.jpg
  frontend/src/assets/imagelogin.png
  frontend/src/assets/logo.svg
  frontend/src/assets/react.svg
  frontend/src/components/Navbar.jsx
  frontend/src/error-page.jsx
  frontend/src/eventdetail.jsx
  frontend/src/hackathon.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/message.css
  frontend/src/message.jsx
  frontend/src/personal.css
  frontend/src/personal.jsx
  frontend/src/profile.css
  frontend/src/profile.jsx
  frontend/tailwind.config.js
  frontend/vite.config.js
  frontend/yarn.lock
  package.json
  prisma/migrations/20241121103949_hackathon_image/migration.sql
  prisma/schema.prisma
  src/controllers/userController.ts
  src/index.ts
Labels: enhancement, Not-ready

#23 Feature: User Rating
  .env
  bun.lockb
  prisma/migrations/20241123135005_user_rating/migration.sql
  prisma/schema.prisma
  src/controllers/ratingController.ts
  src/index.ts
Labels: enhancement, Ready to merge

#25 Feature : Personal preference
  prisma/migrations/20241124090731_personal/migration.sql
  prisma/migrations/20241124091311_change_typo/migration.sql
  prisma/migrations/20241124091339_typo_personal/migration.sql
  prisma/migrations/20241124092849_personal_type/migration.sql
  prisma/schema.prisma
  src/controllers/personalController.ts
  src/index.ts
Labels: enhancement

#32 Page/Message
  .gitignore
  frontend/public/Celesca.png
  frontend/public/HY.png
  frontend/public/undraw_friends.svg
  frontend/src/components/ChatBox.jsx
  frontend/src/components/ChatList.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/main.jsx
  frontend/src/message.jsx
  src/controllers/messageController.ts
  src/controllers/webSocketController.ts
  src/index.ts
Labels: enhancement, Ready to merge

#34 Fix/Team Table
  prisma/migrations/20241126070645_maxmember/migration.sql
  prisma/migrations/20241126071505_typo_member/migration.sql
  prisma/schema.prisma
  src/controllers/teamController.ts
Labels: bug

#39 Feature : EventDetail and Rating
  frontend/src/Rating.jsx
  frontend/src/eventdetail.jsx
  src/controllers/ratingController.ts
  src/controllers/teamController.ts
  src/controllers/userController.ts
Labels: enhancement, Ready to merge
